version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build React app
      - npm run build
      - echo Build Docker image
      - docker build -t 838180512863.dkr.ecr.us-east-2.amazonaws.com/brain-task-app:latest .
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 838180512863.dkr.ecr.us-east-2.amazonaws.com
      - docker push 838180512863.dkr.ecr.us-east-2.amazonaws.com/brain-task-app:latest
